export const config = {
  REACT_APP_HTTP_PROTOCOL: process.env.REACT_APP_HTTP_PROTOCOL,
  REACT_APP_REGISTRY_FRONTEND_PORT:
    process.env.REACT_APP_REGISTRY_FRONTEND_PORT,
  REACT_APP_ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
};
